# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  workingDir: './Chapter 11/Catalog'
  solutionPath: './Chapter 11/Catalog/Catalog.API.sln'
steps:
- task: DotNetCoreInstaller@2
  displayName: 'Install .net core 3.0 (preview)'
  inputs:
    version: '3.1.100'
- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    command: 'build'
    projects: $(solutionPath)
- task: DotNetCoreCLI@2
  displayName: 'Testing'
  inputs:
    command: 'test'
    workingDirectory: $(workingDir)
