version: "3.7"
services:
  catalog_api:
    container_name: catalog_api
    build:
      context: .
    env_file:
      - .env
    networks:
      - my_network
    ports:
      - 5000:5000
    depends_on:
      - catalog_db
      - catalog_esb

  catalog_db:
    container_name: catalog_db
    image: microsoft/mssql-server-linux
    env_file:
      - .env
    networks:
      - my_network
  catalog_esb:
    container_name: catalog_esb
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my_network
networks:
  my_network:
    driver: bridge